### PR TITLE
Temp

### PR DESCRIPTION
**Pull request by Fr0stb1t3**
Created a front end homepage using React js. Using tsparticles as background. It is currently a separate instance other than the server intended to avoid accidental access to the server. Needs a SVG to be added for Mascots. Route not yet created between React and Nodejs.

### CODE REVIEW

**Comment by Sunny619** [comment]
The design is good but not scalable.

1.  Make the animation a simple trail that follows your cursor. Having many instances of trail slows down after many of them have been spawned.
2.  Make the design simplistic and functional. Not loading it with unnecessary bloatware.
3.  Make the elements more distinguishable boundaries or something.
4. Something like this, but u can do anything u like, just more distinguishable.
review

Coming to the file organization. Its totally messed up. We literally have two separate embedded projects in one another. We have two instances of gitignore, package.json and node_modules too.

1. Combine them and reduce redundancy. 
2.  Figure out a way on how to make them work together.
3. Follow a good design pattern for file organisation, its totally messed up as of now.
4. The public folder contains unnecessary files. Make sure to remove them.
5. Read up on react versions and decide which version we need to follow as there are some compatibility issues.

The design LGTM.
Waiting for others to review and we can decide on whether to merge.
@Fr0stb1t3 U can maybe create a new pull request with the required changes, after everyone has reviewed and suggested changes to this PR.

**Review by Sunny619 — CHANGES_REQUESTED** [review]
Make the animation a simple trail that follows your cursor. Having many instances of trail slows down after many of them have been spawned.
Make the design simplistic and functional. Not loading it with unnecessary bloatware.
Make the elements more distinguishable boundaries or something.

Figure out a way on how to make them work together.
Follow a good design pattern for file organisation, its totally messed up as of now.
The public folder contains unnecessary files. Make sure to remove them.

**Comment by Fr0stb1t3** [comment]
> Make the animation a simple trail that follows your cursor. Having many instances of trail slows down after many of them have been spawned. Make the design simplistic and functional. Not loading it with unnecessary bloatware. Make the elements more distinguishable boundaries or something.
> 
> Figure out a way on how to make them work together. Follow a good design pattern for file organisation, its totally messed up as of now. The public folder contains unnecessary files. Make sure to remove them.

- I'll try reducing the animations needed for the homepage, but in order to have react to work along with our current ejs server, the React app needs to be inside the server Project. the Routes needed to connect between the client and server can't be separate. [https://www.freecodecamp.org/news/how-to-create-a-react-app-with-a-node-backend-the-complete-guide/#:~:text=Tools%20You%20Will%20Need%201%20Step%201%3A%20Create,Deploy%20your%20app%20to%20the%20web%20with%20Heroku](url)

- I'll try removing the extra gitIgnore and merging its contents with the existing one. 

- And the Spawning is not infinite. the old instances get destroyed after a number of instances are created. giving the effect of infinite spawning. 
- UI enhancements noted will make them if this build is working on Render

**Comment by Sunny619** [comment]
> * I'll try removing the extra gitIgnore and merging its contents with the existing on

The spawn should always originate from the cursor position and not from the middle of the screen. 
Any spawned instance must be deleted from view as well as from the memory after not more than 2s at max. 
Or have a single instance with a trail follow the cursor. Look at the memory usage in dev tools stats and figure out which works best. 
But spawn at the middle is a complete NO NO from me. 
Take your time, there is no hurry on the Frontend part. 
Try learning design methodology and React best practices, before making further advancements to the projects.
Just jumping in is a good strategy to start learning(for personal projects), but while collaborating, code should be organized in a way that is accepted by the community standards and readable for other collaborators.

**Comment by Sunny619** [comment]
> * And the Spawning is not infinite. the old instances get destroyed after a number of instances are created. giving the effect of infinite spawning.

The spawn should always originate from the cursor position and not from the middle of the screen.
Any spawned instance must be deleted from view as well as from the memory after not more than 2s at max.
Or have a single instance with a trail follow the cursor. Look at the memory usage in dev tools stats and figure out which works best.
But spawn at the middle is a complete NO NO from me.
Take your time, there is no hurry on the Frontend part.
Try learning design methodology and React best practices, before making further advancements to the projects.
Just jumping in is a good strategy to start learning(for personal projects), but while collaborating, code should be organized in a way that is accepted by the community standards and readable for other collaborators.

**Comment by Sunny619** [comment]
> * And the Spawning is not infinite. the old instances get destroyed after a number of instances are created. giving the effect of infinite spawning.

The spawn should always originate from the cursor position and not from the middle of the screen.
Any spawned instance must be deleted from view as well as from the memory after not more than 2s at max.
Or have a single instance with a trail follow the cursor. Look at the memory usage in dev tools stats and figure out which works best.
But spawn at the middle is a complete NO NO from me.
Take your time, there is no hurry on the Frontend part.
Try learning design methodology and React best practices, before making further advancements to the projects.
Just jumping in is a good strategy to start learning(for personal projects), but while collaborating, code should be organized in a way that is accepted by the community standards and readable for other collaborators.

**Comment by Sunny619** [comment]
> * And the Spawning is not infinite. the old instances get destroyed after a number of instances are created. giving the effect of infinite spawning.

- The spawn should always originate from the cursor position and not from the middle of the screen.

- Any spawned instance must be deleted from view as well as from the memory after not more than 2s at max.

- Or have a single instance with a trail follow the cursor. Look at the memory usage in dev tools stats and figure out which works best.

- But spawn at the middle is a complete NO NO from me.

- Take your time, there is no hurry on the Frontend part.

- Try learning design methodology and React best practices, before making further advancements to the projects.

- Just jumping in is a good strategy to start learning(for personal projects), but while collaborating, code should be organized in a way that is accepted by the community standards and readable for other collaborators.

**Pull request closed without merging**
